sudo: false
language: python
cache: pip

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "pypy"

env:
  - DJANGO=1.7
  - DJANGO=1.8
  - DJANGO=1.9
  - DJANGO=1.10

matrix:
  exclude:
    - python: "3.5"
      env: DJANGO=1.7

install:
  - pip install Django==$DJANGO
  - pip install coverage django-nose codecov

script:
  - "python manage.py test --settings=tests.settings"
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
